[Feature] Discord Webhook Functionality
alexjustesen/speedtest-tracker pull request #1196
Opened 2024-02-20 21:12 UTC by jonezy35

## 📃 Description

This PR adds functionality to support Discord webhook notifications. Closes Discord channel in #40 and satisfies user requests in #754 

## 🪵 Changelog

### ➕ Added

- Discord option in UI for notifications
- Discord listener for speedtest notifications on all runs
- Discord listener for speedtest notifications on thresholds being met

### ✏️ Changed

N/A

### 🔧 Fixed

N/A

### 🗑️ Removed

N/A

## 📷 Screenshots

![discord_speedtest](https://github.com/alexjustesen/speedtest-tracker/assets/103131545/d8fe5bf1-34ed-4b0e-aef7-110b47a330e9)

2024-02-21 07:04 UTC, masterwishx commented
@alexjustesen can it be merged now ?

2024-02-21 12:23 UTC, alexjustesen requested changes

2024-02-21 12:23 UTC, alexjustesen commented on app/Filament/Pages/Settings/NotificationPage.php
> +
Can you move the section up to below "Database", want to keep these in alphabetical order.

2024-02-21 12:23 UTC, alexjustesen commented on app/Listeners/SpeedtestCompletedListener.php
> +
Please remove this extra line

2024-02-21 12:23 UTC, alexjustesen commented on app/Listeners/Threshold/AbsoluteListener.php
> +        }
Add an extra line after the if statement to give it some breathing room

2024-02-21 12:23 UTC, alexjustesen commented on app/Listeners/Threshold/AbsoluteListener.php
> +                    $payload = [
Add an extra line before assigning the payload, I'm a fan of code breathing room.

2024-02-21 12:23 UTC, alexjustesen commented on app/Listeners/Threshold/AbsoluteListener.php
> +                    foreach ($failedThresholds as $metric => $result) {
Add an extra line before the foreach loop

2024-02-21 12:23 UTC, alexjustesen commented on database/migrations/2024_02_19_000000_create_discord_notification_settings.php
> +};
Need an extra line at the end of the file

2024-02-21 12:24 UTC, alexjustesen commented
@jonezy35 nice work! I left some formatting comments and looks like the Linter wants some additional changes.

If you want to lint locally run `sail bin duster lint --using=pint -v` before committing changes.

2024-02-21 16:37 UTC, jonezy35 commented
> @jonezy35 nice work! I left some formatting comments and looks like the Linter wants some additional changes.
> 
> If you want to lint locally run `sail bin duster lint --using=pint -v` before committing changes.

@alexjustesen all issues should be fixed now. Made the syntax changes you requested and resolved all lint errors locally before committing. Thanks for the local lint syntax

2024-02-21 16:38 UTC, jonezy35 commented
Might think about adding the lint check to the development guide so in the future those errors can be handled before the PR is opened

2024-02-21 16:39 UTC, alexjustesen commented
Good call, I'll do that and review the PR again tonight.

2024-02-22 14:36 UTC, alexjustesen approved these changes

2024-02-22 14:36 UTC, merged

2024-02-22 14:39 UTC, jonezy35 commented
@alexjustesen thanks! I'm going to start looking into the slack functionality as well now that I have this down. What is the process/ timeline for the docker container to update with the new functionality once a PR is merged?

2024-02-22 14:54 UTC, alexjustesen commented
@jonezy35 going to move this chat to a discussion, got some additional thoughts and changes I need to make and don't want to lose it in the PR.

2024-02-22 15:00 UTC, alexjustesen commented
Let's chat here: https://github.com/alexjustesen/speedtest-tracker/discussions/1220