Improvements user resource
alexjustesen/speedtest-tracker pull request #1732
Opened 2024-09-26 19:15 UTC by JohnDivam

## 📃 Description

A short description of the pull request changes should go here and the sections below should list in detail all changes. You can remove the sections you don't need.

## 🪵 Changelog

### ➕ Added

- one
- two

### ✏️ Changed

- one
- two

### 🔧 Fixed

- one
- two

### 🗑️ Removed

- one
- two

## 📷 Screenshots

If this PR has any UI/UX changes it's strongly suggested you add screenshots here.

2024-10-09 13:49 UTC, alexjustesen requested changes

2024-10-09 13:49 UTC, alexjustesen commented on app/Filament/Resources/UserResource.php
> +                                Forms\Components\TextInput::make('password')->label('Password')
🤏 change, we can drop the label if the field name from `make()` is the same.

2024-10-17 08:44 UTC, JohnDivam commented
Yes, Got it! We can remove @alexjustesen

2024-11-08 12:16 UTC, alexjustesen approved these changes

2024-11-08 12:24 UTC, merged