[Feature] Add Discord notifications for threshold failures with user mentions
alexjustesen/speedtest-tracker pull request #1898
Opened 2024-12-07 00:41 UTC by rubencosta13

## 📃 Description

This pull request introduces a new feature to notify Discord users when a speedtest threshold is breached. The notifications include the breached metric details and support user mentions in Discord.

## 🪵 Changelog

### ➕ Added

- Feature to send Discord notifications when speedtest thresholds are breached.
- Support for user mentions in Discord messages.

### ✏️ Changed

- Updated Blade template for structured threshold breach notifications.
- Modified notification settings to include user mention functionality.

## 📷 Screenshots

<img width="807" alt="image" src="https://github.com/user-attachments/assets/80720076-31f7-434e-8b23-96dc5461f187">

2024-12-07 00:48 UTC, rubencosta13 commented
I didn't like how the UI turned out to be, possibly a WIP for me...

2024-12-07 09:00 UTC, svenvg93 commented
my two cents, would not be nicer to have the Discord User id as part of the `Add to Webhooks` . So the user can choose per set webhook if there is a user ID wanted or not?

2024-12-07 11:09 UTC, rubencosta13 commented
> my two cents, would not be nicer to have the Discord User id as part of the `Add to Webhooks` . So the user can choose per set webhook if there is a user ID wanted or not?

Yup, kinda makes more sense! TY

2024-12-07 12:29 UTC, svenvg93 commented
The you also don't need the separate settings for it as it will be saved in the json with the discord url :)

2024-12-24 15:29 UTC, alexjustesen requested changes

2024-12-24 15:29 UTC, alexjustesen commented on app/Filament/Pages/Settings/NotificationPage.php
> +                                                            ->helperText('This should be the numeric User ID from Discord (e.g., 123456789012345678)'),
Instead of using the `helperText` can you add a [hint](https://filamentphp.com/docs/3.x/forms/fields/getting-started#adding-a-hint-next-to-the-label) that says "Get User ID" with a link out to the Discord docs here: https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID#h_01HRSTXPS5H5D7JBY2QKKPVKNA

2024-12-24 15:29 UTC, alexjustesen commented on resources/views/discord/speedtest-threshold.blade.php
> +@if (!empty($mentionUser))
Not required but you could also use the new `@blank` and `@filled` directives merged in #1951.

2024-12-24 15:31 UTC, alexjustesen commented
@rubencosta13 if you still want to merge this in just a small change to help with finding a user's ID in Discord. If you no longer want to merge feel free to close the PR.

2025-01-01 17:19 UTC, rubencosta13 commented
> @rubencosta13 if you still want to merge this in just a small change to help with finding a user's ID in Discord. If you no longer want to merge feel free to close the PR.

Will do it this week!
Happy 2025

2025-02-03 18:18 UTC, alexjustesen commented
Closing as it's been a month, feel free to open a new PR with updates when you're ready.

2025-02-03 18:18 UTC, closed without merging